version: '3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  web:
    build: .
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

  webpack:
    build: ./frontend
    command: [npm, run, start]
    volumes:
      - ./frontend:/frontend
    ports:
      - "3500:3500"

